spring.application.name=LeaveService
server.port=8080

jwt-secret=3K8mP2nQ5rS8tU1vW4xY7zA0bC3dE6fG9hJ2kL5mN9pQ1rS4tU7vO0xY6zA6bC9d
Hmac-Key=0+lXy9v7dMsE5dfqW1Edab0v5ViEfWtzTBsEuQw3aN8=
Default-Password=5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

spring.datasource.url=jdbc:mysql://localhost:3306/leave_service_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false